Parser
brianc2730/scrypt pull request #3
Opened 2023-10-18 22:40 UTC by YanezAndrew

Our code is done for the Checkpoint #1 on Gradescope. Please add comments to help improve the code!

2023-10-19 21:59 UTC, brianc2730 commented on src/lib/Parser.cpp
> +bool Parser::isParenthesisBalance() {
Delete this function since it isn't getting called anywhere.

2023-10-19 22:09 UTC, brianc2730 commented on src/lib/Parser.cpp
> +            solution += "*";
Add a comment summarizing what this function does. Include what std::string solution represents as well

2023-10-19 22:09 UTC, brianc2730 commented on src/lib/Parser.cpp
> +*/
Delete this comment

2023-10-19 22:10 UTC, brianc2730 commented on src/lib/Parser.cpp
> +    return result;
Delete these comments

2023-10-19 22:16 UTC, brianc2730 commented on src/lib/node.h
> +
Capitalize file node.h and node.cpp file name

2023-10-19 22:17 UTC, brianc2730 commented on src/lib/Parser.h
> +    void algorithim();
algorithm is spelled wrong. Probably should change it to the correct spelling in both the function declaration and definition

2023-10-19 22:21 UTC, KauriMai commented on src/lib/Parser.cpp
> +void Parser::inOrderTraversalPrint(Node* currNode){
Delete Extra comments here, and on line 4 too

2023-10-19 22:22 UTC, brianc2730 commented on src/lib/Parser.h
> +    std::stack<Token> pStack;
Delete this variable. pStack is never used

2023-10-19 22:26 UTC, brianc2730 commented on src/lib/Parser.cpp
> +        } else if (tokenList[i].getValue() == "(") {
What does this else if do? Potentially delete if it isn't actually any condition

2023-10-19 22:30 UTC, KauriMai requested changes

2023-10-19 22:30 UTC, KauriMai commented on src/lib/Parser.cpp
> +/*
Remove empty function comments

2023-10-19 22:30 UTC, KauriMai commented on src/lib/Parser.cpp
> +bool Parser::error(int i) {
Exxplain different error types

2023-10-19 22:30 UTC, KauriMai commented on src/lib/Parser.cpp
> +                std::cout << "Unexpected token at line "<< tokenList[i].getLine() << " column " << tokenList[i].getCol() << ": " << tokenList[i].getValue() << std::endl;
Can we move all these errors to the "error" function?

2023-10-19 22:30 UTC, KauriMai commented on src/lib/Parser.cpp
> +            std::cout << this->print(calculator.root) << std::endl;
SHould we be calling delete within this function?
Wouldn't it be better to call it in a separate one? or even in thee destructor, so that we can move print to parse.cpp

2023-10-19 22:30 UTC, KauriMai commented on src/lib/Parser.cpp
> +Parser::Parser(std::vector<Token> vToken){
Maybe try to construct the AST and check for errors here in the constructor?

2023-10-19 22:30 UTC, KauriMai commented on src/parse.cpp
> +
Maybe call functions more in here instead of having one function that does everything?
- allows for better reusability


```suggestion
Parser parse(lex.getTokens); //creates AST and checks for errors
std:: cout << parse.print() << '\n'; //prints in infix notation
std:: cout <<parse.calculate() << '\n'; // prints end result
delete parse; // deletes AST and cleans memory
```

2023-10-19 22:43 UTC, brianc2730 commented on src/lib/node.h
> +class Node {
Perhaps make node a struct. Having a class node where everything is public doesn't make any sense.

2023-10-19 22:44 UTC, brianc2730 commented on src/lib/AST.h
> +class AST {
One of two options.
1) Either make AST a struct since everything is technically public right now.
2) Make the Node* root private and have a getRoot accessor function that is public. This allows for encapsulation and does not allow other classes to just have access to the root directly.

2023-10-19 22:47 UTC, brianc2730 requested changes
Code functionality looks good! Moving some code around and deleting unnecessary functions will allow for better organization as well as reusability in the future.

2023-10-20 03:04 UTC, YanezAndrew commented on src/lib/node.h
> +class Node {
For now I will leave everything public, but eventually I want to make member variables private so that we can ensure the data cannot be accessed by any function accidentally.

2023-10-20 03:05 UTC, YanezAndrew commented on src/lib/Parser.cpp
> +        } else if (tokenList[i].getValue() == "(") {
Moves the current pointer up a node if it is not the root. I wrote a comment for it, but this is very necessary.

2023-10-20 03:07 UTC, YanezAndrew commented on src/lib/Parser.cpp
> +            std::cout << this->print(calculator.root) << std::endl;
I think we should keep the delete inside the parser for now. The goal in the future is to totally abstract the process of constructing the AST and doing the abstraction which is why I think it is important to contain everything within one function.

2023-10-20 03:27 UTC, YanezAndrew commented on src/lib/Parser.cpp
> +                std::cout << "Unexpected token at line "<< tokenList[i].getLine() << " column " << tokenList[i].getCol() << ": " << tokenList[i].getValue() << std::endl;
Yes!

2023-10-20 03:30 UTC, YanezAndrew reviewed
Thanks for your comments, it really helped in improving the flow of the code!

2023-10-20 05:04 UTC, brianc2730 approved these changes
Thanks for the changes! Code looks good now!

2023-10-20 05:11 UTC, KauriMai commented
Good job on implementing the changes. Looks good to me!

2023-10-20 05:19 UTC, KauriMai approved these changes
Looks good!

2023-10-20 05:20 UTC, merged